/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
} from "ethers";
import {
  Contract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "@ethersproject/contracts";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";

interface AutomationCompatibleInterface extends ethers.utils.Interface {
  functions: {
    "checkUpkeep(bytes)": FunctionFragment;
    "performUpkeep(bytes)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "checkUpkeep",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "performUpkeep",
    values: [BytesLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "checkUpkeep",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "performUpkeep",
    data: BytesLike
  ): Result;

  events: {};
}

export class AutomationCompatible extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  on(event: EventFilter | string, listener: Listener): this;
  once(event: EventFilter | string, listener: Listener): this;
  addListener(eventName: EventFilter | string, listener: Listener): this;
  removeAllListeners(eventName: EventFilter | string): this;
  removeListener(eventName: any, listener: Listener): this;

  interface: AutomationCompatibleInterface;

  functions: {
    checkUpkeep(
      checkData: BytesLike,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "checkUpkeep(bytes)"(
      checkData: BytesLike,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    performUpkeep(
      performData: BytesLike,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "performUpkeep(bytes)"(
      performData: BytesLike,
      overrides?: Overrides
    ): Promise<ContractTransaction>;
  };

  checkUpkeep(
    checkData: BytesLike,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "checkUpkeep(bytes)"(
    checkData: BytesLike,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  performUpkeep(
    performData: BytesLike,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "performUpkeep(bytes)"(
    performData: BytesLike,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  callStatic: {
    checkUpkeep(
      checkData: BytesLike,
      overrides?: CallOverrides
    ): Promise<
      [boolean, string] & { upkeepNeeded: boolean; performData: string }
    >;

    "checkUpkeep(bytes)"(
      checkData: BytesLike,
      overrides?: CallOverrides
    ): Promise<
      [boolean, string] & { upkeepNeeded: boolean; performData: string }
    >;

    performUpkeep(
      performData: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;

    "performUpkeep(bytes)"(
      performData: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {};

  estimateGas: {
    checkUpkeep(
      checkData: BytesLike,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "checkUpkeep(bytes)"(
      checkData: BytesLike,
      overrides?: Overrides
    ): Promise<BigNumber>;

    performUpkeep(
      performData: BytesLike,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "performUpkeep(bytes)"(
      performData: BytesLike,
      overrides?: Overrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    checkUpkeep(
      checkData: BytesLike,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "checkUpkeep(bytes)"(
      checkData: BytesLike,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    performUpkeep(
      performData: BytesLike,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "performUpkeep(bytes)"(
      performData: BytesLike,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;
  };
}
