/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
} from "ethers";
import {
  Contract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "@ethersproject/contracts";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";

interface VRFCoordinatorV2InterfaceInterface extends ethers.utils.Interface {
  functions: {
    "acceptSubscriptionOwnerTransfer(uint64)": FunctionFragment;
    "addConsumer(uint64,address)": FunctionFragment;
    "cancelSubscription(uint64,address)": FunctionFragment;
    "createSubscription()": FunctionFragment;
    "getRequestConfig()": FunctionFragment;
    "getSubscription(uint64)": FunctionFragment;
    "pendingRequestExists(uint64)": FunctionFragment;
    "removeConsumer(uint64,address)": FunctionFragment;
    "requestRandomWords(bytes32,uint64,uint16,uint32,uint32)": FunctionFragment;
    "requestSubscriptionOwnerTransfer(uint64,address)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "acceptSubscriptionOwnerTransfer",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "addConsumer",
    values: [BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "cancelSubscription",
    values: [BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "createSubscription",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getRequestConfig",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getSubscription",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "pendingRequestExists",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "removeConsumer",
    values: [BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "requestRandomWords",
    values: [BytesLike, BigNumberish, BigNumberish, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "requestSubscriptionOwnerTransfer",
    values: [BigNumberish, string]
  ): string;

  decodeFunctionResult(
    functionFragment: "acceptSubscriptionOwnerTransfer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "addConsumer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "cancelSubscription",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createSubscription",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getRequestConfig",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getSubscription",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "pendingRequestExists",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "removeConsumer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "requestRandomWords",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "requestSubscriptionOwnerTransfer",
    data: BytesLike
  ): Result;

  events: {};
}

export class VRFCoordinatorV2Interface extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  on(event: EventFilter | string, listener: Listener): this;
  once(event: EventFilter | string, listener: Listener): this;
  addListener(eventName: EventFilter | string, listener: Listener): this;
  removeAllListeners(eventName: EventFilter | string): this;
  removeListener(eventName: any, listener: Listener): this;

  interface: VRFCoordinatorV2InterfaceInterface;

  functions: {
    acceptSubscriptionOwnerTransfer(
      subId: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "acceptSubscriptionOwnerTransfer(uint64)"(
      subId: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    addConsumer(
      subId: BigNumberish,
      consumer: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "addConsumer(uint64,address)"(
      subId: BigNumberish,
      consumer: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    cancelSubscription(
      subId: BigNumberish,
      to: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "cancelSubscription(uint64,address)"(
      subId: BigNumberish,
      to: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    createSubscription(overrides?: Overrides): Promise<ContractTransaction>;

    "createSubscription()"(overrides?: Overrides): Promise<ContractTransaction>;

    getRequestConfig(
      overrides?: CallOverrides
    ): Promise<[number, number, string[]]>;

    "getRequestConfig()"(
      overrides?: CallOverrides
    ): Promise<[number, number, string[]]>;

    getSubscription(
      subId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, BigNumber, string, string[]] & {
        balance: BigNumber;
        reqCount: BigNumber;
        owner: string;
        consumers: string[];
      }
    >;

    "getSubscription(uint64)"(
      subId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, BigNumber, string, string[]] & {
        balance: BigNumber;
        reqCount: BigNumber;
        owner: string;
        consumers: string[];
      }
    >;

    pendingRequestExists(
      subId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    "pendingRequestExists(uint64)"(
      subId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    removeConsumer(
      subId: BigNumberish,
      consumer: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "removeConsumer(uint64,address)"(
      subId: BigNumberish,
      consumer: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    requestRandomWords(
      keyHash: BytesLike,
      subId: BigNumberish,
      minimumRequestConfirmations: BigNumberish,
      callbackGasLimit: BigNumberish,
      numWords: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "requestRandomWords(bytes32,uint64,uint16,uint32,uint32)"(
      keyHash: BytesLike,
      subId: BigNumberish,
      minimumRequestConfirmations: BigNumberish,
      callbackGasLimit: BigNumberish,
      numWords: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    requestSubscriptionOwnerTransfer(
      subId: BigNumberish,
      newOwner: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "requestSubscriptionOwnerTransfer(uint64,address)"(
      subId: BigNumberish,
      newOwner: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;
  };

  acceptSubscriptionOwnerTransfer(
    subId: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "acceptSubscriptionOwnerTransfer(uint64)"(
    subId: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  addConsumer(
    subId: BigNumberish,
    consumer: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "addConsumer(uint64,address)"(
    subId: BigNumberish,
    consumer: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  cancelSubscription(
    subId: BigNumberish,
    to: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "cancelSubscription(uint64,address)"(
    subId: BigNumberish,
    to: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  createSubscription(overrides?: Overrides): Promise<ContractTransaction>;

  "createSubscription()"(overrides?: Overrides): Promise<ContractTransaction>;

  getRequestConfig(
    overrides?: CallOverrides
  ): Promise<[number, number, string[]]>;

  "getRequestConfig()"(
    overrides?: CallOverrides
  ): Promise<[number, number, string[]]>;

  getSubscription(
    subId: BigNumberish,
    overrides?: CallOverrides
  ): Promise<
    [BigNumber, BigNumber, string, string[]] & {
      balance: BigNumber;
      reqCount: BigNumber;
      owner: string;
      consumers: string[];
    }
  >;

  "getSubscription(uint64)"(
    subId: BigNumberish,
    overrides?: CallOverrides
  ): Promise<
    [BigNumber, BigNumber, string, string[]] & {
      balance: BigNumber;
      reqCount: BigNumber;
      owner: string;
      consumers: string[];
    }
  >;

  pendingRequestExists(
    subId: BigNumberish,
    overrides?: CallOverrides
  ): Promise<boolean>;

  "pendingRequestExists(uint64)"(
    subId: BigNumberish,
    overrides?: CallOverrides
  ): Promise<boolean>;

  removeConsumer(
    subId: BigNumberish,
    consumer: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "removeConsumer(uint64,address)"(
    subId: BigNumberish,
    consumer: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  requestRandomWords(
    keyHash: BytesLike,
    subId: BigNumberish,
    minimumRequestConfirmations: BigNumberish,
    callbackGasLimit: BigNumberish,
    numWords: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "requestRandomWords(bytes32,uint64,uint16,uint32,uint32)"(
    keyHash: BytesLike,
    subId: BigNumberish,
    minimumRequestConfirmations: BigNumberish,
    callbackGasLimit: BigNumberish,
    numWords: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  requestSubscriptionOwnerTransfer(
    subId: BigNumberish,
    newOwner: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "requestSubscriptionOwnerTransfer(uint64,address)"(
    subId: BigNumberish,
    newOwner: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  callStatic: {
    acceptSubscriptionOwnerTransfer(
      subId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    "acceptSubscriptionOwnerTransfer(uint64)"(
      subId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    addConsumer(
      subId: BigNumberish,
      consumer: string,
      overrides?: CallOverrides
    ): Promise<void>;

    "addConsumer(uint64,address)"(
      subId: BigNumberish,
      consumer: string,
      overrides?: CallOverrides
    ): Promise<void>;

    cancelSubscription(
      subId: BigNumberish,
      to: string,
      overrides?: CallOverrides
    ): Promise<void>;

    "cancelSubscription(uint64,address)"(
      subId: BigNumberish,
      to: string,
      overrides?: CallOverrides
    ): Promise<void>;

    createSubscription(overrides?: CallOverrides): Promise<BigNumber>;

    "createSubscription()"(overrides?: CallOverrides): Promise<BigNumber>;

    getRequestConfig(
      overrides?: CallOverrides
    ): Promise<[number, number, string[]]>;

    "getRequestConfig()"(
      overrides?: CallOverrides
    ): Promise<[number, number, string[]]>;

    getSubscription(
      subId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, BigNumber, string, string[]] & {
        balance: BigNumber;
        reqCount: BigNumber;
        owner: string;
        consumers: string[];
      }
    >;

    "getSubscription(uint64)"(
      subId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, BigNumber, string, string[]] & {
        balance: BigNumber;
        reqCount: BigNumber;
        owner: string;
        consumers: string[];
      }
    >;

    pendingRequestExists(
      subId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<boolean>;

    "pendingRequestExists(uint64)"(
      subId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<boolean>;

    removeConsumer(
      subId: BigNumberish,
      consumer: string,
      overrides?: CallOverrides
    ): Promise<void>;

    "removeConsumer(uint64,address)"(
      subId: BigNumberish,
      consumer: string,
      overrides?: CallOverrides
    ): Promise<void>;

    requestRandomWords(
      keyHash: BytesLike,
      subId: BigNumberish,
      minimumRequestConfirmations: BigNumberish,
      callbackGasLimit: BigNumberish,
      numWords: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "requestRandomWords(bytes32,uint64,uint16,uint32,uint32)"(
      keyHash: BytesLike,
      subId: BigNumberish,
      minimumRequestConfirmations: BigNumberish,
      callbackGasLimit: BigNumberish,
      numWords: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    requestSubscriptionOwnerTransfer(
      subId: BigNumberish,
      newOwner: string,
      overrides?: CallOverrides
    ): Promise<void>;

    "requestSubscriptionOwnerTransfer(uint64,address)"(
      subId: BigNumberish,
      newOwner: string,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {};

  estimateGas: {
    acceptSubscriptionOwnerTransfer(
      subId: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "acceptSubscriptionOwnerTransfer(uint64)"(
      subId: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    addConsumer(
      subId: BigNumberish,
      consumer: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "addConsumer(uint64,address)"(
      subId: BigNumberish,
      consumer: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    cancelSubscription(
      subId: BigNumberish,
      to: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "cancelSubscription(uint64,address)"(
      subId: BigNumberish,
      to: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    createSubscription(overrides?: Overrides): Promise<BigNumber>;

    "createSubscription()"(overrides?: Overrides): Promise<BigNumber>;

    getRequestConfig(overrides?: CallOverrides): Promise<BigNumber>;

    "getRequestConfig()"(overrides?: CallOverrides): Promise<BigNumber>;

    getSubscription(
      subId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "getSubscription(uint64)"(
      subId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    pendingRequestExists(
      subId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "pendingRequestExists(uint64)"(
      subId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    removeConsumer(
      subId: BigNumberish,
      consumer: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "removeConsumer(uint64,address)"(
      subId: BigNumberish,
      consumer: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    requestRandomWords(
      keyHash: BytesLike,
      subId: BigNumberish,
      minimumRequestConfirmations: BigNumberish,
      callbackGasLimit: BigNumberish,
      numWords: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "requestRandomWords(bytes32,uint64,uint16,uint32,uint32)"(
      keyHash: BytesLike,
      subId: BigNumberish,
      minimumRequestConfirmations: BigNumberish,
      callbackGasLimit: BigNumberish,
      numWords: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    requestSubscriptionOwnerTransfer(
      subId: BigNumberish,
      newOwner: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "requestSubscriptionOwnerTransfer(uint64,address)"(
      subId: BigNumberish,
      newOwner: string,
      overrides?: Overrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    acceptSubscriptionOwnerTransfer(
      subId: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "acceptSubscriptionOwnerTransfer(uint64)"(
      subId: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    addConsumer(
      subId: BigNumberish,
      consumer: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "addConsumer(uint64,address)"(
      subId: BigNumberish,
      consumer: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    cancelSubscription(
      subId: BigNumberish,
      to: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "cancelSubscription(uint64,address)"(
      subId: BigNumberish,
      to: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    createSubscription(overrides?: Overrides): Promise<PopulatedTransaction>;

    "createSubscription()"(
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    getRequestConfig(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "getRequestConfig()"(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getSubscription(
      subId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "getSubscription(uint64)"(
      subId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    pendingRequestExists(
      subId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "pendingRequestExists(uint64)"(
      subId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    removeConsumer(
      subId: BigNumberish,
      consumer: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "removeConsumer(uint64,address)"(
      subId: BigNumberish,
      consumer: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    requestRandomWords(
      keyHash: BytesLike,
      subId: BigNumberish,
      minimumRequestConfirmations: BigNumberish,
      callbackGasLimit: BigNumberish,
      numWords: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "requestRandomWords(bytes32,uint64,uint16,uint32,uint32)"(
      keyHash: BytesLike,
      subId: BigNumberish,
      minimumRequestConfirmations: BigNumberish,
      callbackGasLimit: BigNumberish,
      numWords: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    requestSubscriptionOwnerTransfer(
      subId: BigNumberish,
      newOwner: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "requestSubscriptionOwnerTransfer(uint64,address)"(
      subId: BigNumberish,
      newOwner: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;
  };
}
