/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer } from "ethers";
import { Provider } from "@ethersproject/providers";

import type { AutomationCompatibleInterface } from "../AutomationCompatibleInterface";

export class AutomationCompatibleInterface__factory {
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): AutomationCompatibleInterface {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as AutomationCompatibleInterface;
  }
}

const _abi = [
  {
    inputs: [
      {
        internalType: "bytes",
        name: "checkData",
        type: "bytes",
      },
    ],
    name: "checkUpkeep",
    outputs: [
      {
        internalType: "bool",
        name: "upkeepNeeded",
        type: "bool",
      },
      {
        internalType: "bytes",
        name: "performData",
        type: "bytes",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes",
        name: "performData",
        type: "bytes",
      },
    ],
    name: "performUpkeep",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];
